#!/usr/bin/env python3
import rospy
from std_msgs.msg import String

def callback(data):
    rospy.loginfo("받은 메시지: %s", data.data)

rospy.init_node('listener')
sub = rospy.Subscriber('/key_input', String, callback)

rospy.spin()  # 콜백을 계속 대기
