# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from md/md_robot_msg2.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class md_robot_msg2(genpy.Message):
  _md5sum = "de9f2ebda4cc402f2af0c2ecca0409bf"
  _type = "md/md_robot_msg2"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 interval_time
int32 x_pos
int32 y_pos
int16 angule
uint8 US_1
uint8 US_2
uint8 US_3
uint8 US_4
uint8 platform_state
int16 linear_velocity
int16 angular_velocity
float32 input_voltage


"""
  __slots__ = ['interval_time','x_pos','y_pos','angule','US_1','US_2','US_3','US_4','platform_state','linear_velocity','angular_velocity','input_voltage']
  _slot_types = ['float64','int32','int32','int16','uint8','uint8','uint8','uint8','uint8','int16','int16','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       interval_time,x_pos,y_pos,angule,US_1,US_2,US_3,US_4,platform_state,linear_velocity,angular_velocity,input_voltage

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(md_robot_msg2, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.interval_time is None:
        self.interval_time = 0.
      if self.x_pos is None:
        self.x_pos = 0
      if self.y_pos is None:
        self.y_pos = 0
      if self.angule is None:
        self.angule = 0
      if self.US_1 is None:
        self.US_1 = 0
      if self.US_2 is None:
        self.US_2 = 0
      if self.US_3 is None:
        self.US_3 = 0
      if self.US_4 is None:
        self.US_4 = 0
      if self.platform_state is None:
        self.platform_state = 0
      if self.linear_velocity is None:
        self.linear_velocity = 0
      if self.angular_velocity is None:
        self.angular_velocity = 0
      if self.input_voltage is None:
        self.input_voltage = 0.
    else:
      self.interval_time = 0.
      self.x_pos = 0
      self.y_pos = 0
      self.angule = 0
      self.US_1 = 0
      self.US_2 = 0
      self.US_3 = 0
      self.US_4 = 0
      self.platform_state = 0
      self.linear_velocity = 0
      self.angular_velocity = 0
      self.input_voltage = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_d2ih5B2hf().pack(_x.interval_time, _x.x_pos, _x.y_pos, _x.angule, _x.US_1, _x.US_2, _x.US_3, _x.US_4, _x.platform_state, _x.linear_velocity, _x.angular_velocity, _x.input_voltage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 31
      (_x.interval_time, _x.x_pos, _x.y_pos, _x.angule, _x.US_1, _x.US_2, _x.US_3, _x.US_4, _x.platform_state, _x.linear_velocity, _x.angular_velocity, _x.input_voltage,) = _get_struct_d2ih5B2hf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_d2ih5B2hf().pack(_x.interval_time, _x.x_pos, _x.y_pos, _x.angule, _x.US_1, _x.US_2, _x.US_3, _x.US_4, _x.platform_state, _x.linear_velocity, _x.angular_velocity, _x.input_voltage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 31
      (_x.interval_time, _x.x_pos, _x.y_pos, _x.angule, _x.US_1, _x.US_2, _x.US_3, _x.US_4, _x.platform_state, _x.linear_velocity, _x.angular_velocity, _x.input_voltage,) = _get_struct_d2ih5B2hf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d2ih5B2hf = None
def _get_struct_d2ih5B2hf():
    global _struct_d2ih5B2hf
    if _struct_d2ih5B2hf is None:
        _struct_d2ih5B2hf = struct.Struct("<d2ih5B2hf")
    return _struct_d2ih5B2hf
